### ISSUE TITLE
unable to access the direct URL of the file (https://drive.google.com/uc?id=1A2B3C4D5E6F7G8H9I0J)

### ISSUE THREAD

**Issue by zhanqx1024** [LTU-RAI/ExplorationRRT#4]
Description:
I am encountering an issue while trying to download a file from Google Drive using gdown. Here is the error message I received:

HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1A2B3C4D5E6F7G8H9I0J (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0c4ad7fb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

Additionally, I am unable to access the direct URL of the file (https://drive.google.com/uc?id=1A2B3C4D5E6F7G8H9I0J) via a web browser, so I suspect the issue could be related to connectivity or regional restrictions.

**Comment by haotongluo** [comment]
I can send you these files

**Comment by zhanqx1024** [comment]
> I can send you these files

I am writing to kindly seek your assistance. Currently, I am having difficulties downloading the following files using the provided gdown commands:

gdown --id 1TDbXF9He_LXYY57Xo3tOxvEVYH3kPtS8
gdown --id 1y7BDt0tjK9Ml7MlTxUwOTG8ZygO_dpI0
Would it be possible for you to send these files to me directly via email（qxzhan@tongji.edu.cn）? I would greatly appreciate your help.

Please feel free to contact me if there is anything I need to do from my side. Thank you in advance for your support!

qxzhan@tongji.edu.cn

**Comment by aakapatel** [comment]
Hi @zhanqx1024,

Thank you for your interest in our work. 
I am not able to reproduce this issue. May be G-drive isn't accessible in your region for some reason. Please let me know if you have not received the models zip, I can send it. 

At some point we will move the models to a reliable download source. 

Thanks,
Akash
