### ISSUE TITLE
Failed to build Docker image using osrf/ros:noetic-desktop-full-focal - Connection Refused Error

### ISSUE THREAD

**Issue by zhanqx1024** [LTU-RAI/ExplorationRRT#5]
I encountered an issue while building a Docker image using the following command:
sudo docker build --build-arg USERNAME=$(whoami) -t errt_test .
The build process fails when it tries to load metadata for the osrf/ros:noetic-desktop-full-focal image. Below is the full log:
[+] Building 21.1s (3/3) FINISHED                               docker:default
 => [internal] load .dockerignore                                         0.0s
 => => transferring context: 2B                                           0.0s
 => [internal] load build definition from Dockerfile                      0.0s
 => => transferring dockerfile: 7.45kB                                    0.0s
 => ERROR [internal] load metadata for docker.io/osrf/ros:noetic-deskto  21.0s
------
 > [internal] load metadata for docker.io/osrf/ros:noetic-desktop-full-focal:
------
Dockerfile:1
--------------------
   1 | >>> FROM osrf/ros:noetic-desktop-full-focal
   2 |     
   3 |     ENV LANG C.UTF-8
--------------------
ERROR: failed to solve: osrf/ros:noetic-desktop-full-focal: failed to do request: Head "https://registry-1.docker.io/v2/osrf/ros/manifests/noetic-desktop-full-focal": dial tcp 88.191.249.182:443: connect: connection refused

**Comment by aakapatel** [comment]
Hello, Thank you for your interest in out work. 
I cannot reproduce this issue. The base image is still available and not deprecated. May be internet issue?

Feel free to re open the issue if unresolved. 

Thanks,
Akash
